display_name: Merge Chat Example

icon: assets/logo.png

keywords:
  - Chat
  - Proof Of Concept

generic_name: Merge Chat Example

# supported mime types that can be opened using this application
# supported_mime_type:
#   - audio/mpeg

metainfo: linux/packaging/mergeChatExample.appdata.xml

categories:
  - Network

startup_notify: true

# You can specify the shared libraries that you want to bundle with your app
#
# flutter_distributor automatically detects the shared libraries that your app
# depends on, but you can also specify them manually here.
# 
# The following example shows how to bundle the libcurl library with your app.
#
# include:
#   - libcurl.so.4
#include: []