# script_template: "custom-inno-setup-script.iss"
app_id: c23a30a2-e9de-44f5-8abb-5bb416160ed1
publisher_name: Arran Ubels
publisher_url: https://github.com/arran4/merge_chat_example
display_name: Merge Chat Example
create_desktop_icon: true
launch_at_startup: true
# install_dir_name: "D:\\MERGE-CHAT-EXAMPLE"
locales:
  - en
